-- ============================================================================
-- StockPlatform
-- Migration: 0020_reference_tables.sql
-- Description: Core reference tables
-- ============================================================================

-- ============================================================================
-- MARKETS
-- ============================================================================

CREATE TABLE core.markets
(
    market_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    country_code   CHAR(2),
    timezone       VARCHAR(64) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_markets_name UNIQUE (name)
);

-- ============================================================================
-- EXCHANGES
-- ============================================================================

CREATE TABLE core.exchanges
(
    exchange_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id      BIGINT NOT NULL,
    mic            VARCHAR(8) NOT NULL,
    code           VARCHAR(16) NOT NULL,
    name           TEXT NOT NULL,
    timezone       VARCHAR(64) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_exchanges_market
        FOREIGN KEY (market_id)
        REFERENCES core.markets (market_id),
    CONSTRAINT uq_exchanges_mic UNIQUE (mic),
    CONSTRAINT uq_exchanges_code UNIQUE (code)
);

-- ============================================================================
-- ASSET TYPES
-- ============================================================================

CREATE TABLE core.asset_types
(
    asset_type_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(32) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_asset_types_name UNIQUE (name)
);

-- ============================================================================
-- CURRENCIES
-- ============================================================================

CREATE TABLE core.currencies
(
    currency_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           CHAR(3) NOT NULL,
    name           TEXT NOT NULL,
    symbol         VARCHAR(8),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_currencies_code UNIQUE (code)
);

-- ============================================================================
-- ASSETS
-- ============================================================================

CREATE TABLE core.assets
(
    asset_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker          VARCHAR(16) NOT NULL,
    provider_symbol VARCHAR(16),
    name            TEXT NOT NULL,
    display_name    TEXT,
    exchange_id     BIGINT NOT NULL,
    asset_type_id   BIGINT NOT NULL,
    currency_id     BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_assets_exchange
        FOREIGN KEY (exchange_id)
        REFERENCES core.exchanges (exchange_id),
    CONSTRAINT fk_assets_asset_type
        FOREIGN KEY (asset_type_id)
        REFERENCES core.asset_types (asset_type_id),
    CONSTRAINT fk_assets_currency
        FOREIGN KEY (currency_id)
        REFERENCES core.currencies (currency_id),
    CONSTRAINT uq_assets_exchange_ticker
        UNIQUE (exchange_id, ticker)
);
